name: Run Python Script and Commit Results

on:
  # 定时运行，例如每天凌晨 00:00 UTC
  schedule:
    - cron: '0 0 * * *'
  # 手动触发
  workflow_dispatch:

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python Script
      run: |
        python main.py

    - name: Commit Results
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add .
        git commit -m "Update results from workflow run"
        git push
